### ISSUE TITLE
How to use a trained model?

### ISSUE THREAD

**Issue by catweis** [kireygroup/fastsom#21]
Again thank you very much for this very cool repo. I really enjoy working with it.
What would be the best way to use a trained model in your framework? The point is that the training is very time-consuming and therefore I need to save the results. 
I (now) know how to get the trained SOM-model (and to save it). Is it possible to mount it into "learn"? The background is that there are already all functions etc. (like get_preds) I would like to use.
Thank you very much in forward for your answer.

**Comment by rsayn** [comment]
Hi, this project is based on Fast.ai, and I tried to keep the same signature as their Learner class.
You can refer to their documentation here: https://docs.fast.ai/learner.html
The `Learner.export` method and `load_learner` function should help you to (respectively) serialize/deserialize your SomLearner in Pickle format 😄

**Comment by catweis** [comment]
Thank you very much for your fast answer. Unfortunately neither export nor save does work for me.
There is always this error:

_Traceback (most recent call last):
  File "E:\..\venv1\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-17f43ffa7e06>", line 2, in <module>
    learn.export(f_name)
  File "E:\..\venv1\lib\site-packages\fastsom\learn\learn.py", line 230, in export
    super().export(file, destroy)
  File "E:\..\venv1\lib\site-packages\fastai\learner.py", line 545, in export
    torch.save(self, self.path/fname, pickle_module=pickle_module, pickle_protocol=pickle_protocol)
  File "E:\..\venv1\lib\site-packages\torch\serialization.py", line 367, in save
    _check_dill_version(pickle_module)
  File "E:\..\venv1\lib\site-packages\torch\serialization.py", line 322, in _check_dill_version
    if pickle_module.__name__ == 'dill':
AttributeError: 'bool' object has no attribute '__name__'_

I tried it on different systems and after re-installation. Furthermore, with "pure" fastai learners it does not occur.

**Comment by catweis** [comment]
Saving the model alone with torch.save again works. Thus, it seems for me to be no problem of the SOM-model.
